# Addresses rubric criteria 2-4 by providing shared attribution/reporting
# helpers built on the audited price and backtest outputs.
"""Shared analysis utilities for Whitmore attribution and reporting.

References:
- Whitmore IPS / Guidelines in the repo.
- Bailey & López de Prado (2014), Deflated Sharpe Ratio:
  https://www.davidhbailey.com/dhbpapers/deflated-sharpe.pdf

Point-in-time safety:
- These helpers operate on already-generated historical outputs. They are used
  for ex-post analysis and reporting, not for live signal generation.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from taa_project.config import ALL_SAA, CORE, NONTRAD, OUTPUT_DIR, SATELLITE
from taa_project.data_loader import load_prices, log_returns


TRADING_DAYS_PER_YEAR = 252
RISK_FREE_RATE = 0.02
EULER_MASCHERONI = 0.5772156649


def tier_map() -> dict[str, str]:
    """Return the Whitmore tier classification by SAA sleeve.

    Inputs:
    - None.

    Outputs:
    - Mapping from ticker to `Core`, `Satellite`, or `Non-Traditional`.

    Citation:
    - Whitmore IPS `Guidelines.md` strategic allocation table.

    Point-in-time safety:
    - Safe. This is static IPS metadata.
    """

    mapping = {asset: "Core" for asset in CORE}
    mapping.update({asset: "Satellite" for asset in SATELLITE})
    mapping.update({asset: "Non-Traditional" for asset in NONTRAD})
    return mapping


def simple_asset_returns(prices: pd.DataFrame | None = None) -> pd.DataFrame:
    """Return audited simple asset returns derived from Task 1 log returns.

    Inputs:
    - `prices`: optional price dataframe. If omitted, load the audited prices.

    Outputs:
    - Simple-return dataframe aligned to the full price calendar.

    Citation:
    - `tasks.md`, Step 2 return-calculation rules.

    Point-in-time safety:
    - Safe. Returns are a deterministic transform of the audited historical
      price panel.
    """

    price_frame = load_prices().loc[:, ALL_SAA] if prices is None else prices.loc[:, ALL_SAA]
    log_ret = log_returns(price_frame)
    return np.exp(log_ret) - 1.0


def load_output_csv(path: Path, index_col: str | int | None = 0, parse_dates: bool = True) -> pd.DataFrame:
    """Load a CSV output file with optional datetime-index parsing.

    Inputs:
    - `path`: CSV file path.
    - `index_col`: index column spec passed to `pandas.read_csv`.
    - `parse_dates`: whether to parse the index column as datetimes.

    Outputs:
    - Dataframe loaded from disk.

    Citation:
    - pandas documentation: https://pandas.pydata.org/

    Point-in-time safety:
    - Safe. This is an ex-post output loader only.
    """

    if index_col is None:
        return pd.read_csv(path)
    parse = [index_col] if parse_dates else False
    return pd.read_csv(path, index_col=index_col, parse_dates=parse)


def load_core_outputs(output_dir: Path = OUTPUT_DIR) -> dict[str, pd.DataFrame]:
    """Load the primary portfolio output artifacts used in later tasks.

    Inputs:
    - `output_dir`: directory containing generated CSV artifacts.

    Outputs:
    - Dictionary of loaded output dataframes.

    Citation:
    - Whitmore project outputs generated by Tasks 2, 3, 6, and 7.

    Point-in-time safety:
    - Safe. This is an ex-post analysis loader.
    """

    return {
        "saa_weights": load_output_csv(output_dir / "saa_weights.csv"),
        "saa_returns": pd.read_csv(output_dir / "saa_returns.csv", parse_dates=["Date"]).set_index("Date"),
        "bm1_weights": load_output_csv(output_dir / "bm1_weights.csv"),
        "bm1_returns": pd.read_csv(output_dir / "bm1_returns.csv", parse_dates=["Date"]).set_index("Date"),
        "bm2_weights": load_output_csv(output_dir / "bm2_weights.csv"),
        "bm2_returns": pd.read_csv(output_dir / "bm2_returns.csv", parse_dates=["Date"]).set_index("Date"),
        "oos_weights": pd.read_csv(output_dir / "oos_weights.csv", parse_dates=["decision_date"]).set_index("decision_date"),
        "oos_returns": pd.read_csv(output_dir / "oos_returns.csv", parse_dates=["date", "decision_date"]).set_index("date"),
        "oos_regimes": pd.read_csv(output_dir / "oos_regimes.csv", parse_dates=["date"]).set_index("date"),
    }


def decision_weights_to_daily_target(
    decision_weights: pd.DataFrame,
    daily_index: pd.DatetimeIndex,
) -> pd.DataFrame:
    """Forward-fill sparse rebalance targets onto a daily analysis calendar.

    Inputs:
    - `decision_weights`: rebalance-date target weights indexed by decision
      date and containing `ALL_SAA` columns.
    - `daily_index`: target daily analysis index.

    Outputs:
    - Daily target-weight dataframe on `daily_index`.

    Citation:
    - Whitmore Tasks 2, 3, and 6 rebalance schedule requirements.

    Point-in-time safety:
    - Safe for ex-post reporting. It extends each realized target only forward
      until the next rebalance date.
    """

    weights = decision_weights.loc[:, ALL_SAA].copy()
    expanded = weights.reindex(weights.index.union(daily_index)).sort_index().ffill()
    return expanded.reindex(daily_index).fillna(0.0)


def monthly_decision_weights_to_daily_target(
    decision_weights: pd.DataFrame,
    daily_index: pd.DatetimeIndex,
) -> pd.DataFrame:
    """Backward-compatible alias for `decision_weights_to_daily_target`.

    Inputs:
    - `decision_weights`: rebalance-date target weights.
    - `daily_index`: target daily analysis index.

    Outputs:
    - Daily target-weight dataframe on `daily_index`.

    Citation:
    - Whitmore Task 6 monthly TAA decision schedule.

    Point-in-time safety:
    - Safe. Delegates to the generic ex-post daily target expander.
    """

    return decision_weights_to_daily_target(decision_weights, daily_index)


def decision_weights_to_daily_holdings(
    decision_weights: pd.DataFrame,
    asset_returns: pd.DataFrame,
) -> pd.DataFrame:
    """Reconstruct daily holdings from sparse rebalance targets.

    Inputs:
    - `decision_weights`: rebalance-date target dataframe indexed by decision
      date and containing `ALL_SAA` columns.
    - `asset_returns`: simple asset returns indexed by realized trading dates.

    Outputs:
    - Daily holdings dataframe indexed by realized return dates.

    Citation:
    - Whitmore Tasks 2, 3, and 6 simulation design.

    Point-in-time safety:
    - Safe for ex-post analysis. This reconstructs holdings from already-fixed
      rebalance decisions and realized returns after those decisions.
    """

    if decision_weights.empty:
        return pd.DataFrame(columns=ALL_SAA, dtype=float)

    sparse_targets = decision_weights.loc[:, ALL_SAA].copy()
    decision_index = pd.DatetimeIndex(sparse_targets.index)
    holdings_rows: list[pd.Series] = []
    daily_returns = asset_returns.loc[:, ALL_SAA].dropna(how="all")

    for idx, decision_date in enumerate(decision_index):
        next_decision = decision_index[idx + 1] if idx + 1 < len(decision_index) else None
        period_index = daily_returns.index[daily_returns.index > decision_date]
        if next_decision is not None:
            period_index = period_index[period_index <= next_decision]

        current_weights = sparse_targets.loc[decision_date].astype(float).reindex(ALL_SAA).fillna(0.0)
        for date in period_index:
            holdings_rows.append(current_weights.rename(date))
            gross = 1.0 + daily_returns.loc[date].reindex(ALL_SAA).fillna(0.0)
            post_move_value = current_weights * gross
            denominator = float(post_move_value.sum())
            current_weights = post_move_value / denominator if denominator > 0 else current_weights.copy()

    if not holdings_rows:
        return pd.DataFrame(columns=ALL_SAA, dtype=float)
    return pd.DataFrame(holdings_rows).astype(float)


def monthly_decision_weights_to_daily_holdings(
    decision_weights: pd.DataFrame,
    asset_returns: pd.DataFrame,
) -> pd.DataFrame:
    """Backward-compatible alias for `decision_weights_to_daily_holdings`.

    Inputs:
    - `decision_weights`: rebalance-date target weights.
    - `asset_returns`: simple asset returns.

    Outputs:
    - Daily holdings dataframe indexed by realized return dates.

    Citation:
    - Whitmore Task 6 monthly TAA decision schedule.

    Point-in-time safety:
    - Safe. Delegates to the generic ex-post holdings reconstruction helper.
    """

    return decision_weights_to_daily_holdings(decision_weights, asset_returns)


def extract_rebalance_targets(
    weights_df: pd.DataFrame,
    returns_df: pd.DataFrame,
    flag_column: str = "rebalance_flag",
) -> pd.DataFrame:
    """Extract the sparse rebalance targets from a dense daily weight schedule.

    Inputs:
    - `weights_df`: daily target-weight dataframe.
    - `returns_df`: returns dataframe containing a rebalance-flag column.
    - `flag_column`: column in `returns_df` that marks rebalance dates.

    Outputs:
    - Sparse dataframe of rebalance-date targets indexed by rebalance date.

    Citation:
    - Whitmore Tasks 2 and 3 portfolio simulation outputs.

    Point-in-time safety:
    - Safe for ex-post analysis. This only recovers the dates on which the
      already-simulated portfolio intentionally traded.
    """

    if flag_column not in returns_df.columns:
        raise KeyError(f"Missing rebalance flag column: {flag_column}")

    rebalance_dates = returns_df.index[returns_df[flag_column].fillna(0).astype(int) == 1]
    return weights_df.reindex(rebalance_dates).loc[:, ALL_SAA].dropna(how="all")


def constant_weight_schedule(weights: dict[str, float], daily_index: pd.DatetimeIndex) -> pd.DataFrame:
    """Create a dense daily constant-weight schedule on the SAA universe.

    Inputs:
    - `weights`: sparse weight dictionary.
    - `daily_index`: target daily index.

    Outputs:
    - Daily constant-weight dataframe indexed by `daily_index`.

    Citation:
    - Whitmore IPS benchmark definitions.

    Point-in-time safety:
    - Safe. These are ex-post benchmark schedules.
    """

    row = pd.Series(weights, dtype=float).reindex(ALL_SAA).fillna(0.0)
    return pd.DataFrame([row] * len(daily_index), index=daily_index)


def annualized_return(returns: pd.Series) -> float:
    """Compute the annualized geometric return from daily simple returns.

    Inputs:
    - `returns`: daily simple return series.

    Outputs:
    - Annualized geometric return.

    Citation:
    - Standard performance-metric convention used in the Whitmore rubric.

    Point-in-time safety:
    - Ex-post metric only.
    """

    clean = returns.dropna()
    if clean.empty:
        return float("nan")
    growth = float((1.0 + clean).prod())
    years = len(clean) / TRADING_DAYS_PER_YEAR
    return growth ** (1.0 / years) - 1.0 if years > 0 else float("nan")


def annualized_volatility(returns: pd.Series) -> float:
    """Compute annualized volatility from daily simple returns.

    Inputs:
    - `returns`: daily simple return series.

    Outputs:
    - Annualized standard deviation of returns.

    Citation:
    - Standard performance-metric convention used in the Whitmore rubric.

    Point-in-time safety:
    - Ex-post metric only.
    """

    clean = returns.dropna()
    return float(clean.std(ddof=0) * math.sqrt(TRADING_DAYS_PER_YEAR)) if not clean.empty else float("nan")


def sharpe_ratio(returns: pd.Series, risk_free_rate: float = RISK_FREE_RATE) -> float:
    """Compute the annualized Sharpe ratio using daily simple returns.

    Inputs:
    - `returns`: daily simple return series.
    - `risk_free_rate`: annual risk-free rate used for excess returns.

    Outputs:
    - Annualized Sharpe ratio.

    Citation:
    - Standard performance-metric convention used in the Whitmore rubric.

    Point-in-time safety:
    - Ex-post metric only.
    """

    ann_ret = annualized_return(returns)
    ann_vol = annualized_volatility(returns)
    return (ann_ret - risk_free_rate) / ann_vol if ann_vol and not np.isnan(ann_vol) and ann_vol > 0 else float("nan")


def max_drawdown(returns: pd.Series) -> float:
    """Compute maximum drawdown from daily simple returns.

    Inputs:
    - `returns`: daily simple return series.

    Outputs:
    - Minimum value of the drawdown curve.

    Citation:
    - Standard performance-metric convention used in the Whitmore rubric.

    Point-in-time safety:
    - Ex-post metric only.
    """

    clean = returns.dropna()
    if clean.empty:
        return float("nan")
    wealth = (1.0 + clean).cumprod()
    drawdown = wealth / wealth.cummax() - 1.0
    return float(drawdown.min())


def drawdown_curve(returns: pd.Series) -> pd.Series:
    """Compute the full drawdown curve from daily simple returns.

    Inputs:
    - `returns`: daily simple return series.

    Outputs:
    - Daily drawdown series aligned to the non-missing return history.

    Citation:
    - Standard performance-metric convention used in the Whitmore rubric.

    Point-in-time safety:
    - Ex-post metric only.
    """

    clean = returns.dropna()
    if clean.empty:
        return pd.Series(dtype=float)
    wealth = (1.0 + clean).cumprod()
    return wealth / wealth.cummax() - 1.0


def cumulative_growth_index(returns: pd.Series, start_value: float = 100.0) -> pd.Series:
    """Convert a return series into a cumulative-growth index.

    Inputs:
    - `returns`: daily simple return series.
    - `start_value`: starting index value.

    Outputs:
    - Growth index series beginning at `start_value`.

    Citation:
    - Whitmore Task 8 chart requirement for index-100 growth curves.

    Point-in-time safety:
    - Ex-post reporting transform only.
    """

    clean = returns.dropna()
    if clean.empty:
        return pd.Series(dtype=float)
    return start_value * (1.0 + clean).cumprod()


def rolling_annualized_volatility(returns: pd.Series, window: int = TRADING_DAYS_PER_YEAR) -> pd.Series:
    """Compute rolling annualized volatility from daily simple returns.

    Inputs:
    - `returns`: daily simple return series.
    - `window`: trailing window length in trading days.

    Outputs:
    - Rolling annualized volatility series.

    Citation:
    - Whitmore Task 8 chart requirement for 12-month rolling volatility.

    Point-in-time safety:
    - Ex-post reporting transform only.
    """

    clean = returns.dropna()
    if clean.empty:
        return pd.Series(dtype=float)
    return clean.rolling(window=window, min_periods=max(window // 2, 20)).std(ddof=0) * math.sqrt(TRADING_DAYS_PER_YEAR)


def calmar_ratio(returns: pd.Series) -> float:
    """Compute the Calmar ratio from daily simple returns.

    Inputs:
    - `returns`: daily simple return series.

    Outputs:
    - Annualized return divided by absolute max drawdown.

    Citation:
    - Standard performance-metric convention used in the Whitmore rubric.

    Point-in-time safety:
    - Ex-post metric only.
    """

    ann_ret = annualized_return(returns)
    drawdown = max_drawdown(returns)
    return ann_ret / abs(drawdown) if pd.notna(drawdown) and drawdown < 0 else float("nan")


def sortino_ratio(returns: pd.Series, mar: float = 0.0) -> float:
    """Annualized Sortino ratio.

    Inputs:
    - `returns`: daily simple return series.
    - `mar`: minimum acceptable return, annualized, defaults to 0.

    Outputs:
    - (annualized excess return over MAR) / (annualized downside deviation below MAR).
      Returns NaN when downside deviation is zero.

    Citation:
    - Sortino & Van der Meer (1991), "Downside Risk", Journal of Portfolio Management.
      https://jpm.pm-research.com/content/17/4/27

    Point-in-time safety:
    - Ex-post metric only.
    """

    clean = returns.dropna()
    if clean.empty:
        return float("nan")
    daily_mar = (1.0 + mar) ** (1.0 / TRADING_DAYS_PER_YEAR) - 1.0
    excess = clean - daily_mar
    downside = excess.clip(upper=0.0)
    # Use population std with N in denominator (ddof=0), consistent with the
    # Sharpe/vol conventions already used in this module.
    dd = float((downside**2).mean()) ** 0.5
    if dd == 0.0 or not np.isfinite(dd):
        return float("nan")
    ann_excess = annualized_return(clean) - mar
    ann_dd = dd * math.sqrt(TRADING_DAYS_PER_YEAR)
    return ann_excess / ann_dd


def historical_var_95(returns: pd.Series) -> float:
    """Compute the 95% historical Value-at-Risk from daily simple returns.

    Inputs:
    - `returns`: daily simple return series.

    Outputs:
    - Fifth-percentile daily return.

    Citation:
    - Whitmore Task 8 metrics specification.

    Point-in-time safety:
    - Ex-post metric only.
    """

    clean = returns.dropna()
    return float(clean.quantile(0.05)) if not clean.empty else float("nan")


def hit_rate(returns: pd.Series) -> float:
    """Compute the share of positive-return days in a portfolio history.

    Inputs:
    - `returns`: daily simple return series.

    Outputs:
    - Fraction of non-missing days with return strictly greater than zero.

    Citation:
    - Whitmore Task 8 metrics specification.

    Point-in-time safety:
    - Ex-post metric only.
    """

    clean = returns.dropna()
    return float((clean > 0).mean()) if not clean.empty else float("nan")


def years_covered(index: pd.Index) -> float:
    """Return the approximate number of trading years in an index.

    Inputs:
    - `index`: daily return index.

    Outputs:
    - Approximate trading years using a 252-day convention.

    Citation:
    - Standard performance-metric convention used in the Whitmore rubric.

    Point-in-time safety:
    - Ex-post metric helper only.
    """

    return len(index) / TRADING_DAYS_PER_YEAR if len(index) else float("nan")


def turnover_per_year(total_turnover: float, index: pd.Index) -> float:
    """Annualize realized turnover using the observed backtest length.

    Inputs:
    - `total_turnover`: total `|Δw|_1` accumulated over the sample.
    - `index`: daily return index covering the same sample.

    Outputs:
    - Turnover per trading year.

    Citation:
    - Whitmore Task 8 metrics specification.

    Point-in-time safety:
    - Ex-post metric only.
    """

    years = years_covered(index)
    return float(total_turnover / years) if pd.notna(years) and years > 0 else float("nan")


def cost_drag_per_year(total_cost: float, index: pd.Index) -> float:
    """Annualize realized transaction-cost drag over the observed sample.

    Inputs:
    - `total_cost`: sum of realized turnover-cost deductions.
    - `index`: daily return index covering the same sample.

    Outputs:
    - Annualized cost drag in simple-return units.

    Citation:
    - Whitmore Task 8 metrics specification.

    Point-in-time safety:
    - Ex-post metric only.
    """

    years = years_covered(index)
    return float(total_cost / years) if pd.notna(years) and years > 0 else float("nan")


def tier_weight_frame(weights: pd.DataFrame) -> pd.DataFrame:
    """Aggregate a weight dataframe into Whitmore tier totals.

    Inputs:
    - `weights`: asset-weight dataframe containing `ALL_SAA` columns.

    Outputs:
    - Dataframe with `Core`, `Satellite`, and `Non-Traditional` columns.

    Citation:
    - Whitmore IPS aggregate constraint structure.

    Point-in-time safety:
    - Safe for ex-post analysis. This is a deterministic aggregation of
      already-fixed portfolio weights.
    """

    aligned = weights.reindex(columns=ALL_SAA).fillna(0.0)
    return pd.DataFrame(
        {
            "Core": aligned.loc[:, CORE].sum(axis=1),
            "Satellite": aligned.loc[:, SATELLITE].sum(axis=1),
            "Non-Traditional": aligned.loc[:, NONTRAD].sum(axis=1),
        },
        index=aligned.index,
    )


def deflated_sharpe_ratio(returns: pd.Series, n_trials: int) -> float:
    """Compute the Deflated Sharpe Ratio for a daily return series.

    Inputs:
    - `returns`: daily simple return series.
    - `n_trials`: number of tested strategy variants in the trial ledger.

    Outputs:
    - Deflated Sharpe Ratio in `[0, 1]`.

    Citation:
    - Bailey & López de Prado (2014):
      https://www.davidhbailey.com/dhbpapers/deflated-sharpe.pdf

    Point-in-time safety:
    - Ex-post selection-bias adjustment only.
    """

    clean = returns.dropna()
    if len(clean) < 3 or n_trials <= 0:
        return float("nan")

    sr = sharpe_ratio(clean)
    skew = float(stats.skew(clean, bias=False)) if len(clean) > 2 else 0.0
    kurt = float(stats.kurtosis(clean, fisher=False, bias=False)) if len(clean) > 3 else 3.0
    sr_variance = (1.0 - skew * sr + ((kurt - 1.0) / 4.0) * sr**2) / max(len(clean) - 1, 1)
    sr_std = math.sqrt(max(sr_variance, 1e-12))

    quantile_one = stats.norm.ppf(1.0 - 1.0 / n_trials) if n_trials > 1 else 0.0
    quantile_two = stats.norm.ppf(1.0 - 1.0 / (n_trials * math.e)) if n_trials > 1 else 0.0
    expected_max_sr = sr_std * ((1.0 - EULER_MASCHERONI) * quantile_one + EULER_MASCHERONI * quantile_two)
    denominator = math.sqrt(max(1.0 - skew * sr + ((kurt - 1.0) / 4.0) * sr**2, 1e-12))
    z_score = (sr - expected_max_sr) * math.sqrt(max(len(clean) - 1, 1)) / denominator
    return float(stats.norm.cdf(z_score))
